spring.application.name=AvaliaDados

spring.profiles.active=${PROFILES_ACTIVE:dev}

server.port=8080

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000

spring.cloud.openfeign.client.config.colab-data.connectTimeout=500000
spring.cloud.openfeign.client.config.colab-data.readTimeout= 15000000